# WIZFI360-EVB-PICO-AWS-C_BUILD_DEFINE: WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_MAJOR, SDK major version number
set(WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_MAJOR 1)
# WIZFI360-EVB-PICO-AWS-C_BUILD_DEFINE: WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_MINOR, SDK minor version number
set(WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_MINOR 0)
# WIZFI360-EVB-PICO-AWS-C_BUILD_DEFINE: WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_REVISION, SDK version revision
set(WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_REVISION 0)
# WIZFI360-EVB-PICO-AWS-C_BUILD_DEFINE: WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_STRING, SDK version
set(WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_STRING "${WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_MAJOR}.${WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_MINOR}.${WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_REVISION}")

message(STATUS "WizFi360-EVB-Pico-AWS-C SDK version is ${WIZFI360-EVB-PICO-AWS-C_SDK_VERSION_STRING}")
